# Copyright 2019 The Periph Authors. All rights reserved.
# Use of this source code is governed under the Apache License, Version 2.0
# that can be found in the LICENSE file.

os: linux
dist: bionic
language: go
go_import_path: periph.io/x/periph

jobs:
  include:
  - go: 1.14.x
    cache:
      directories:
      - $GOPATH/pkg/mod
      # Cache tools sources.
      #- $GOPATH/src/github\.com/client9
      #- $GOPATH/src/github\.com/google/addlicense
      #- $GOPATH/src/github\.com/gordonklaus
      #- $GOPATH/src/golang\.org
    before_script:
    - echo $TRAVIS_GO_VERSION
    - go get -t -v periph.io/x/periph/...
    - >
      go get -u -v
      github.com/client9/misspell/cmd/misspell
      github.com/google/addlicense
      github.com/gordonklaus/ineffassign
      golang.org/x/tools/go/analysis/passes/shadow/cmd/shadow
    script:
    - >
      echo 'Check Code is well formatted';
      ! gofmt -s -d . | read
    - >
      echo 'Looking for external dependencies:';
      go list -f '{{join .Imports "\n"}}' periph.io/x/periph/... | sort | uniq | grep -v ^periph.io/x/periph | xargs go list -f '{{if not .Standard}}- {{.ImportPath}}{{end}}'
    - >
      echo 'Erroring on external dependencies:';
      ! go list -f '{{join .Imports "\n"}}' periph.io/x/periph/... | sort | uniq | grep -v ^periph.io/x/periph | xargs go list -f '{{if not .Standard}}Remove {{.ImportPath}}{{end}}' | grep -q Remove
    - >
      echo 'Erroring on /host depending on /devices:';
      ! go list -f '{{.ImportPath}} depends on {{join .Imports ", "}}' periph.io/x/periph/host/... | sort | uniq | grep periph.io/x/periph/devices
    - >
      echo 'Erroring on /conn depending on /devices:';
      ! go list -f '{{.ImportPath}} depends on {{join .Imports ", "}}' periph.io/x/periph/conn/... | sort | uniq | grep periph.io/x/periph/devices
    - >
      echo 'Erroring on /conn depending on /host:';
      ! go list -f '{{.ImportPath}} depends on {{join .Imports ", "}}' periph.io/x/periph/conn/... | sort | uniq | grep periph.io/x/periph/host
    - >
      echo 'Erroring on misspelling';
      ! misspell . | grep a
    - >
      echo 'Erroring on inefficient variable assignment:';
      ineffassign .
    - >
      echo 'Erroring on go vet:';
      go vet ./...
    - >
      echo 'Erroring on shadowed variables:';
      ! go vet -vettool=$(which shadow) ./... |& grep -v '"err"' | grep -e '^[^#]'
    - >
      echo 'Running tests with code coverage:';
      go test -covermode=count -coverprofile=coverage.txt ./...
    - >
      echo 'Running tests with race detector:';
      go test -race ./...
    - >
      echo 'Erroring if an executable was committed:';
      if find . -path ./.git -prune -o -type f -executable -print | grep -e . ; then echo 'Do not commit executables'; false; fi
    - >
      echo 'Erroring if a license header is missing:';
      ! addlicense -check . | grep -v '\(cmd/ssd1306/font7x13.go\|conn/duplex_string.go\|devices/lepton/cci/strings_gen.go\|experimental/cmd/periph-web/static/index.html\|experimental/cmd/periph-web/static_prod.go\)' | read
    after_success:
    - bash <(curl -s https://codecov.io/bash)

  - go: 1.7.6
    before_script:
    - echo $TRAVIS_GO_VERSION
    - go get -t -v periph.io/x/periph/...
    script:
    - go test ./...
